server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/easemybooking_auth}
    username: ${DB_USERNAME:auth_user}
    password: ${DB_PASSWORD:auth_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: auth-hikari

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      # Local dev default; Docker overrides below
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  issuer: easemybooking-auth
  #secret: ${JWT_SECRET}
  accessTtlMinutes: ${JWT_ACCESS_TTL_MINUTES:30}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
    allowed-methods: GET,POST,PATCH,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

auth:
  invite:
    admin: "CHANGE_ME_SUPER_SECRET"
    owner: "CHANGE_ME_OWNER_SECRET"
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    # Use the DB container hostname from docker-compose
    url: ${DB_URL:jdbc:postgresql://auth-db:5432/easemybooking_auth}
    username: ${DB_USERNAME:auth_user}
    password: ${DB_PASSWORD:auth_pass}

eureka:
  client:
    serviceUrl:
      # Use the Eureka container hostname from docker-compose
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}

management:
  endpoint:
    health:
      show-details: never



