services:
  postgres-auth:
    image: postgres:17
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: easemybooking_auth
    ports: ["5432:5432"]
    volumes: [auth_pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d easemybooking_auth"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-auth:5432/easemybooking_auth
      DB_USERNAME: auth_user
      DB_PASSWORD: auth_pass
      JWT_SECRET: ${JWT_SECRET:?set_in_.env}
      JWT_ACCESS_TTL_MINUTES: ${JWT_ACCESS_TTL_MINUTES:-30}
      # issuer comes from application.yml (easemybooking-auth), no need to override
    ports: ["8081:8081"]
    depends_on:
      postgres-auth:
        condition: service_healthy

volumes:
  auth_pgdata:
