server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/Desktop/easemybooking-config-repo
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: health,info
